######################################################################
# Automatically generated by qmake (3.0) Thu Jan 19 20:01:44 2017
######################################################################

TEMPLATE = app
TARGET = HelloTest
INCLUDEPATH += .

# Input
SOURCES += main.cpp
